### ISSUE TITLE
Additions to the spy / spy verification APIs

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony#125]
This task is intended as a summary of the currently proposed additions to the spy APIs. This includes #115, #102, #78, #92 and #11.

These are the proposed methods:

- [x] `generates()` - starts generator stubbing (#11)
- [x] <del>`resolvesTo()` - returns a promise that resolves to a value (#78)</del> **not needed**
- [x] <del>`rejectsWith()` - returns a promise that rejects with a value (#78)</del> **not needed**
- [x] <del>`notifies()` - emits a promise notification (#78)</del> **not needed**
- [x] <del>`cancels()` - causes the promise to be cancelled (#78)</del> **not needed**
- [x] <del>`promised()->resolved()` - verifies that a promise resolved to a value (#78)</del> **not needed**
- [x] <del>`promised()->rejected()` - verifies that a promise rejected with a value (#78)</del> **not needed**
- [x] <del>`promised()->notified()` - verifies that the promise emitted a notification (#78)</del> **not needed**
- [x] <del>`promised()->cancelled()` - verifies that the promise was cancelled (#78)</del> **not needed**
- [x] `generated()` - verifies that a spy or call returned a generator (#115) OR
- [x] `generated()->returned()` - verifies that a generator returned a value (#115)
- [x] `generated()->threw()` - verifies that a generator threw an exception (#115)
- [x] `traversed()->used()` - verifies that iteration started (#102)
- [x] `traversed()->consumed()` - verifies that iteration completed (#102)
- [x] `responded()` - verifies that a call "responded" (returned the initial generator or traversable) (also passes for returned non-traversables and regular thrown exceptions) (#92)
- [x] `completed()` - verifies that a call "completed" (similar to `consumed()`, but passes for returned non-traversables and regular thrown exceptions) (#92)

**Comment by ezzatron** [comment]
I've been thinking about an alternate approach to generator, traversable, and promise verification. Perhaps instead of littering the call and spy APIs with lots of verification methods, there could be additional validator interfaces accessible via `generated()`, `produced()` (or similar), and `promised()`.

These validators would have only the methods relevant to each, and would still represent a "verification result", so that they can be used in event order verification.

When a user calls `generated()` for example, this would result in a verification failure unless the spy/call returned a generator. On success, the result would be an event collection containing each of the calls that returned a generator, but it would also implement a generator verification API. This API would allow for method names like `returned()` and `threw()` to be re-used, and only apply to generators.

Typical usage might look something like this:

```php
inOrder(
    $spyA->generated(),
    $spyB->generated()->returned('a')
    $spyC->callAt(1)->generated()->threw()
);
```

There's a side benefit to this approach too, in that these additional validators can be used by both spy validators and individual call validators. This probably means less effort is required to implement these new features.

**Comment by ezzatron** [comment]
1.0 HYPE!!! 🎉
