### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony#216]
I've put together a release roadmap for Phony, with the help of @jmalloc. The time has come to start the process of dropping support for older versions of PHP, and some of the probably-unused integrations. Here's the plan as it stands today:

If you're reading this, and there's anything here that's going to make your life difficult, please comment ASAP. Cheers!

## Address current issues

First, I'll clear the slate of current issues, to prepare for `1.0.0`.

- [x] Bring in the Composer install "magic" needed to get a working Travis build from the [remove-matcher-integrations](https://github.com/eloquent/phony/tree/remove-matcher-integrations) branch.
- [x] Address #214.
- [x] Release `0.14.7`

## 1.0.0, PHP 5 support, and refactoring of third party integrations

Next, I'll release a `1.0.0` version, which will be the place where any PHP 5 support work takes place going forward. Anyone who still needs Phony's PHP 5 support can safely use a `^1` constraint going forward.

- [x] Refactor PHPUnit, SimpleTest, and Pho integrations into separate Composer packages
- [x] Drop support for Phake, Mockery, Prophecy, and Counterpart matchers
- [x] Release `1.0.0`
- [x] Release `1.0.0` of `phony-phpunit`, with support for PHPUnit 4 and 5

## PHPUnit 6 support

I know people are waiting on PHPUnit 6 support, so this should take next priority. There's no way I can feasibly accomplish this until third party integrations have been moved to external repos.

- [x] Release `2.0.0` of `phony-phpunit`, with support for PHPUnit 6

## 2.0.0 and refactoring third party integrations

ASAP after `1.0.0`, I'll release a `2.0.0` version that drops support for PHP 5. This should help ease the maintenance burden of Phony, and reduce a whole bunch of tech debt going forward. Anyone who doesn't need PHP 5 support will be able to use the `^2` constraint.

- [x] Drop support for PHP 5
- [x] Drop support for HHVM <del>versions other than the "current" and "previous" versions [supported on Travis](https://docs.travis-ci.com/user/languages/php/#HHVM-versions-on-Trusty) (currently `3.15` and `3.18`)</del> - HHVM will no longer be supported at all due to [HHVM's change of direction](http://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html)
- [x] Release `2.0.0`

**Comment by ezzatron** [comment]
@darianbr @parkertr @koden-km @shadowhand @enumag FYI

**Comment by ezzatron** [comment]
The important stuff is all done for now. I'll probably wait a little while to make sure there are no major issues with any of the new releases, before moving on to `2.0.0` work.

Check out the mini [migration guide](https://github.com/eloquent/phony/blob/master/CHANGELOG.md#migrating-to-1x) in the changelog for how to get started using the new stuff.

**Comment by ezzatron** [comment]
Due to [HHVM's change of direction](http://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html), HHVM support will be dropped in `2.0.0`.

**Comment by ezzatron** [comment]
[2.0.0](https://github.com/eloquent/phony/releases/2.0.0) is released! 🎉 

Individual integration libraries will follow shortly.
