### ISSUE TITLE
General to-do

### ISSUE THREAD

**Issue by ezzatron** [eloquent/phony#3]
- [x] Refactor out `InvocableUtils`
- [x] Implement matcher auto-detection magic
- [x] Generator spies
- [x] Consider refactoring out 'generated' event
- [x] Assertion return types for order verification
- [x] Fluent interface for cardinality verification (`once()`, `times()`, `never()`, `atLeast()`)
- [x] Generator verifications/assertions
- [x] Order verification/assertion
- [x] Refactor stubs, formalize rules and answers
- [x] Get back to 100% coverage
- [ ] Generator stubs
- [x] Mock builder proxying
- [x] Mock builder factory
- [x] Finish off mock builder tests once mock factory is working
- [ ] Advanced trait mocking (`insteadof` and `as` keywords)
- [x] Mocks
- [x] Partial mocks
- [ ] Flesh out facade matchers etc.
- [ ] Check everything is `@internal`
- [x] Test for constructors not named `__construct` just in case
- [ ] Thoroughly test mocks for reference parameter goodness
